name: Deploy Podcast Feed

on:
  push:
    branches:
      - main
  schedule:
    # Tous les jours à 3h du matin UTC
    - cron: "0 3 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Vérification présence du script
        run: |
          if [ ! -f "update_and_backup_rss.py" ]; then
            echo "❌ Script update_and_backup_rss.py manquant"
            exit 1
          fi

      - name: Run RSS generation script
        run: |
          python3 update_and_backup_rss.py || exit 1

      - name: Commit updated feed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add mr_x.xml backups/ || true
          git commit -m "Auto-regenerate feed via GitHub Action" || echo "Aucun changement à commiter"
          git push || true

      - name: Purge GitHub Pages cache
        run: |
          curl -s -X PURGE https://angles974-tech.github.io/mr-x-podcast/mr_x.xml || true

